### ISSUE TITLE
Testing example rules

### ISSUE THREAD

**Issue by magick93** [gorules/jdm-editor#12]
Hello

I'm trying to test the UI with some of the example rules. I've tried uploading https://github.com/gorules/zen/blob/master/test-data/credit-analysis.json in both FF and Chrome, and in both it was unable to load it. I didnt see any meaningful error in the browser console. Here is what I did see (from Chrome):

![image](https://github.com/gorules/jdm-editor/assets/2173213/cf101ea3-1c3a-4a3a-a123-4f24a9cc38cd)

**Comment by ivanmiletic** [comment]
We will investigate

**Comment by ivanmiletic** [comment]
We will update editor.gorules.io to the latest version next week and open source it
