### ISSUE TITLE
Bug: JDM Rule Graph (Restyled) Editor Allows Node Connections When Disabled

### ISSUE THREAD

**Issue by AlifioDitya** [gorules/jdm-editor#20]
### Issue Description
When using the JDM rule graph editor in read-only mode, specifically while scrolling through different versions of the rules, the editor should not allow any changes to be made, including connecting nodes. However, a bug currently exists where nodes can still be connected even when disabled. This behavior deviates from the expected functionality, where the rule graph editor should be entirely read-only when reviewing rule versions.

### Steps to Reproduce
1. Open the JDM rule graph editor.
2. Open version mode, scroll through different versions of the rules.
3. Attempt to connect nodes within the graph editor.

### Expected Behavior
The rule graph editor should be disabled (or in a read-only state), preventing any modifications, including connecting nodes between different parts of the graph.

### Actual Behavior
Users are able to connect nodes even while in read-only mode, indicating that the editor is not fully disabled.

### Possible Impact
Allowing modifications in view mode could lead to unintended changes or confusion about the current state of rule versions, as users might expect their interactions in this mode to have no effect. I haven't checked on whether or not it impacts the simulator, but be wary of that also.

### Additional Information
- No additional plugins or custom scripts were used that could affect the editor's functionality.
- This issue was identified in the version currently deployed on the GoRules platform demo environment.

If this behavior is expected or it has been fixed, please close this issue. Otherwise, please let me know if more details are needed or if there are any workarounds available in the meantime.  

Thank you!

**Comment by ivanmiletic** [comment]
Will investigate

**Comment by ivanmiletic** [comment]
Issue has been fixed, new version of the cloud, brms and standalone editor will be released today

**Comment by ivanmiletic** [comment]
Released
