### ISSUE TITLE
Export and Import CSV delimit by semi-colon

### ISSUE THREAD

**Issue by jackfrankland** [gorules/jdm-editor#23]
Hi there,

When exporting the CSV from a decision table, this is what I see:
<img width="998" alt="image" src="https://github.com/gorules/jdm-editor/assets/634879/c094c564-06fa-47a3-a7e1-01dce281253b">

When attempting to import a CSV, delimited by comma, this is what I see:
<img width="276" alt="image" src="https://github.com/gorules/jdm-editor/assets/634879/4f5947eb-9d0b-4ac8-bd08-873ae8c488d4">

I'm sure this is a design decision, because you allow commas in the cells' values. However, in Excel and Google Sheets, it's not possible to choose a semi-colon as a delimiter on export. Excel allows you to do it by going to regional language settings. It's too much to ask users to do this in my opinion, and it has the downside of being the default delimiter for every time a user saves a CSV.

Can I suggest allowing Tab-delimited txt files? These can be easily imported and exported.

Cheers. Great tool btw 🙂

**Comment by ivanmiletic** [comment]
Hi thank you for your feedback.
We are working on replacing CSV with Excel in PR #21

**Comment by jackfrankland-cat** [comment]
Fantastic, thanks.

**Comment by jackfrankland** [comment]
Sounds perfect, thanks. Just checking, will this also allow importing of xls?

**Comment by ivanmiletic** [comment]
Hi @jackfrankland yes, you will be able to export decision table into xlsx, modify it and import it back into decision table.

**Comment by ivanmiletic** [comment]
Released with the latest versions of BRMS (1.12.0) and JDM Editor
