### ISSUE TITLE
trying to access my JDM editor from EC2 instance

### ISSUE THREAD

**Issue by himasai9712** [gorules/jdm-editor#41]
I deployed my docker container in ec2 machine and trying to create a decision tree but i cant drag my request dialog into my canvas , how to resolve it?

![image](https://github.com/gorules/jdm-editor/assets/137873839/9bdf04c6-0350-4383-8a59-950567320c50)

And this is my containers

![image](https://github.com/gorules/jdm-editor/assets/137873839/ca6cfbeb-1d76-444a-9fe4-10e7bd2c1fd3)

And this is my docker container logs:

![image](https://github.com/gorules/jdm-editor/assets/137873839/0112e8df-0b7f-4114-bc5d-ca060ba6955c)

**Comment by ivanmiletic** [comment]
Hi @himasai9712 , do you have any browser / UI errors? Which version of BRMS image are you using?

**Comment by himasai9712** [comment]
Hi @ivanmiletic  thanks for replying, I got why this issue is coming I think its not supported by linux ig, when i tried same in my local windows its running fine but i came to another issue while doing so, now the issue is Im trying to communicate with my decision tree  using node here is the screen shot of my decision tree:

![image](https://github.com/gorules/jdm-editor/assets/137873839/ec1b019a-8a27-410e-873e-5239c9c2d72f)

my node code is :

```node
const axios = require('axios');
let data = JSON.stringify({
  "context": {
    "num": 14
  },
  "trace": false
});

let config = {
  method: 'post',
maxBodyLength: Infinity,
  url: 'http://localhost:9080/api/projects/6509ad41-5b2e-40e6-a68f-38559272999d/evaluate/test.json',
  headers: { 
    'Content-Type': 'application/json', 
    'Accept': 'application/json', 
    'X-Access-Token': 'my token'
  },
  data : data
};

axios(config)
.then((response) => {
  console.log(JSON.stringify(response.data));
})
.catch((error) => {
  console.log(error);
});
```

but Im getting output is :

`{"performance":"456.831µs","result":{}}`

my function login in decision tree is :

```node
/**
 * @param input
 * @param {{
 *  dayjs: import('dayjs')
 *  Big: import('big.js').BigConstructor
 * }} helpers
 */
const handler = (input, { dayjs, Big }) => {
  console.log(input.num)

  return input.num;
};
```
I can get output in my simulator but not when i run using code:

![image](https://github.com/gorules/jdm-editor/assets/137873839/b871ab30-d7e1-4d46-8e00-be3c2d438945)

Can you please help me resolve this issue?

**Comment by ivanmiletic** [comment]
Hi, did you save and publish latest decision model?

**Comment by himasai9712** [comment]
Yes i did @ivanmiletic

**Comment by himasai9712** [comment]
@ivanmiletic And what type of os you suggest for running editor in ec2? as it doesnt support linux

**Comment by ivanmiletic** [comment]
Hi @himasai9712 , we do support Linux, both x86_64 and arm but not musl - just gnu libraries. Our compilers are set for: x86_64-unknown-linux-gnu and aarch64-unknown-linux-gnu for linux.

What ec2 machine are you using? Also, do you use just ec2 or some managed services such as EKS or ECS with EC2?

**Comment by ivanmiletic** [comment]
I believe your EC2 should not be of m7g group (those are ARM machines) but either "a" or "i" such as m7i (intel) or m7a (amd).

**Comment by himasai9712** [comment]
@ivanmiletic  hi I'm using t3.medium machine

**Comment by himasai9712** [comment]
I'm using this AMI:

![image](https://github.com/gorules/jdm-editor/assets/137873839/eed2495f-804d-4408-9d4d-8a1974aa5008)

**Comment by ivanmiletic** [comment]
Can you try with default Amazon Linux 2 - or Ubuntu image? Can you also send some error trace from docker if you have?

Next, your machine must have access to a portal.gorules.io for license check - please check if you have any firewall.

Note you can't use same license key as you have locally - you will need either to create a new key or to remove / previous one and create it. One license key can only be used on a single stack / DB.

**Comment by himasai9712** [comment]
@ivanmiletic  ok let me try this..

**Comment by himasai9712** [comment]
@ivanmiletic Hi i tried with machine type:`T3.medium` 

My AMI :

![image](https://github.com/gorules/jdm-editor/assets/137873839/6a87761c-21cf-4429-9205-f0280249945c)

my docker images logs:

![image](https://github.com/gorules/jdm-editor/assets/137873839/5e9e674a-f979-4880-b62a-08035233f3f3)

I'm getting same issue as previous I couldn't drag and drop my core components into the canvas, any other ways to fix this?

**Comment by himasai9712** [comment]
And I have access to the `portal.gorules.io`

here is the screenshot:

![image](https://github.com/gorules/jdm-editor/assets/137873839/77c47a8e-b26e-4e1b-9822-269475a4f0a0)

**Comment by ivanmiletic** [comment]
@himasai9712 From what i can see BRMS is working, if Drag and Drop is the only issue - it seems it is Frontend only related. What browser are you using and can you send me your console log from the browser?

**Comment by himasai9712** [comment]
@ivanmiletic  Im using Brave

**Comment by himasai9712** [comment]
i tried in chrome too

**Comment by stefan-gorules** [comment]
Closing as it's likely a stale issue. Feel free to re-open if you are still facing this. Thanks!

**Comment by himasai9712** [comment]
resolved @stefan-gorules
