### ISSUE TITLE
 WebpackError: TypeError: Cannot read properties of undefined (reading 'ace')

### ISSUE THREAD

**Issue by lucklyt** [gorules/jdm-editor#69]
build failed,cannot find solution

<img width="1230" alt="image" src="https://github.com/user-attachments/assets/cb5e1eff-d1b6-4698-adae-ef9258fee32b">

**Comment by manokaran68** [comment]
@lucklyt were you able to resolve this issue?

**Comment by stefan-gorules** [comment]
Hi, this issue should be resolved as we no longer use `react-ace` and have switch to monaco-editor fully. 

Please let me know if you still face the issue.

**Comment by lucklyt** [comment]
> Hi, this issue should be resolved as we no longer use `react-ace` and have switch to monaco-editor fully.
> 
> Please let me know if you still face the issue.

now is ok,
