### ISSUE TITLE
Boolean control custom nodes

### ISSUE THREAD

**Issue by Cosmo439** [gorules/jdm-editor#79]
I'm working on adding custom nodes to the jdm editor, and I needed a boolean field for my configuration. I set up a simple node, using a boolean input, but any time I tried to render the graph, the config came back as undefined for my boolean field. Looking into your rendering of the form for custom nodes, it looks like you have missed a prop on the Form.Item component to work with checkboxes correctly.

Checkboxes use the checked property instead of the value property for storing the value.

I believe that the change is small, I'm just unable to get your dev environment running for some reason. In this block of code (https://github.com/gorules/jdm-editor/blob/24be2ce73d808b7bc6c6e774a04e1d8b3e852b05/packages/jdm-editor/src/components/decision-graph/nodes/custom-node/index.tsx#L153-L181) you would need to add another check like you do with outerLabel.

```const valuePropName = match({ control })
  .with({ control: 'bool'}, () => 'checked')
  .otherwise(() => undefined)
  
  ... snip other code

  return (
    <Form.Item
      ... snip other properties
      valuePropName={valuePropName}
    >
```

**Comment by stefan-gorules** [comment]
Hi, I believe this is solved by the PR that you've contributed with. I'll close the issue for now, but feel free to reopen if it's not resolved.

Thanks!
