### ISSUE TITLE
Error running Graph Simulator for JDM Editor

### ISSUE THREAD

**Issue by GanNicholas** [gorules/jdm-editor#99]
Encountered the following error when trying to run graph simulator from version 1.20.0 onwards

![image](https://github.com/user-attachments/assets/cdc9f8a6-8b34-4994-8c06-b3f99817e82c)

**Comment by abhay1898** [comment]
This issue is no longer there. Update @gorule/jdmeditor to 1.23.1 version

**Comment by stefan-gorules** [comment]
@abhay1898 Thanks for sharing!
